Name: box3d
Version: 0.1.0.6.g540ea38
Release: 1
Summary: A 3D physics engine for games.
License: MIT
Source: %{name}-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
Requires: gtk3
BuildRequires: cmake, gcc, ninja-build, git, doxygen, gtk3-devel

%description
Box3D is a 3D physics engine for games featuring continuous collision detection
with collision filtering, contact events, support for convex hulls, capsules,
spheres, triangle meshes, and height fields, multiple shapes per body,
ray casts, shape casts, overlap queries, a sensor system, and a character mover
as well as a robust Soft Step rigid body solver with continuous physics for fast
translations and rotations, island-based sleep, various joints including
revolute, prismatic, distance, motor, weld, and wheel with support for limits,
motors, springs, and friction, joint and contact forces, body movement events,
and sleep notifications.

%package devel
Summary: Box3D physics engine development files
Requires: %{name} = %{version}

%description devel
Development tools needed for developing Box3D games and applications.

%package docs
Summary: Box3D HTML and XML documentation
BuildArch: noarch

%description docs
HTML documentation for the Box3D 3D physics engine.

%prep
%setup -c -n %{name}-%{version}

%build
mkdir -p build && cd build
cmake ../%{name}-%{version} \
  -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=%{_prefix} \
  -DBOX3D_DOCS=ON
cmake --build . --config Release --parallel %{?_smp_mflags}
cd ..

%install
rm -rf $RPM_BUILD_ROOT
cd build
DESTDIR=$RPM_BUILD_ROOT cmake --install .
cd ..

# Install documentation generated by Doxygen
mkdir -p $RPM_BUILD_ROOT/%{_docdir}/box3d
cp -ar build/docs/html $RPM_BUILD_ROOT/%{_docdir}/box3d/
cp -ar build/docs/xml $RPM_BUILD_ROOT/%{_docdir}/box3d/

# Strip the release library
strip $RPM_BUILD_ROOT/%{_libdir}/libbox3d.a

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{_libdir}/libbox3d.a

%files devel
%defattr(-,root,root,-)
%{_libdir}/cmake
%{_includedir}/box3d

%files docs
%defattr(-,root,root,-)
%{_docdir}/box3d/
